apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.appOwnerSecretName }}
                  key: DATABASE_URL
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.appOwnerSecretName }}
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.appOwnerSecretName }}
                  key: DATABASE_PASSWORD
            - name: DATABASE_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.appOwnerSecretName }}
                  key: DATABASE_SCHEMA
            - name: GOOGLE_OAUTH2_CLIENT_ID_B64ENC
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-googleClientSecrets
                  key: GOOGLE_OAUTH2_CLIENT_ID_B64ENC
            - name: GOOGLE_OAUTH2_CLIENT_SECRET_B64ENC
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-googleClientSecrets
                  key: GOOGLE_OAUTH2_CLIENT_SECRET_B64ENC