apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-googleClientSecrets
type: Opaque
data:
  GOOGLE_OAUTH2_CLIENT_ID_B64ENC: {{ .Values.google.googleClientID | b64enc | quote }}
  GOOGLE_OAUTH2_CLIENT_SECRET_B64ENC: {{ .Values.google.googleClientSecret | b64enc | quote }}