apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-googleClientSecrets
type: Opaque
data:
  GOOGLE_OAUTH2_CLIENT_ID: {{ .Values.google.googleClientID | quote }}
  GOOGLE_OAUTH2_CLIENT_SECRET: {{ .Values.google.googleClientSecret | quote }}