replicaCount: 1

appVersion: substituted-from-pipeline

image:
  migrationsRepository: substituted-from-pipeline
  repository: substituted-from-pipeline
  tag: substituted-from-pipeline
  pullPolicy: IfNotPresent

containerPort: 8080
serviceType: ClusterIP
servicePort: 80

clusterIssuer: letsencrypt-prod

subdomains: "example.com,example.org"

database:
  appSecretName: "snake-game-prod-app-connection"
  migrationSecretName: "snake-game-prod-owner-connection"